repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      #      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-toml

  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['-iii', '-ll']

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-comprehensions",
          "flake8-mutable",
          "flake8-print",
          "pep8-naming"
        ]

  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: uv run pytest ./event_manager
        always_run: true
        pass_filenames: false
        verbose: true
        language: system

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
