# Generated by Django 5.2 on 2026-04-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("external_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sales",
            options={"managed": False, "ordering": ["price_per_unit"]},
        ),
    ]
