# Generated by Django 5.2 on 2026-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sub_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
